### ISSUE TITLE
Netlify Forms integration in Contact Form

### ISSUE THREAD

**Issue by tigrankhachikyan** [stackbithq/stackbit-theme-hyperspace#1]
Is there any docs on how to integrate Netlify Forms with this theme?
Want to post the submit data from "Get In Touch" page to Netlify?
(Gatsby UI)

Any suggestions?

**Comment by smnh** [comment]
@tigrankhachikyan, the documentation for Netlify Forms can be found [here](https://www.netlify.com/docs/form-handling/)

First, you should create a site from this theme on Stackbit.
Then you edit the code of the generated site (using the GitHub link in your Stackbit dashboard) and the necessary snippet (e.g.: `data-netlify="true"`) to the form.

**Comment by smnh** [comment]
@tigrankhachikyan, the documentation for Netlify Forms can be found [here](https://www.netlify.com/docs/form-handling/)

First, you should create a site from this theme on Stackbit.
Then you should edit the code of the generated site (using the GitHub link in your Stackbit dashboard) with the necessary snippet (e.g.: `data-netlify="true"`) to the form.

If you have selected Gatsby, then the template with the form should be in `src/components/Contact.js` file.
